# Copyright 2024 sby1ce
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
    "cd-core",
    "cd-android",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
# panic = "abort"
# strip = "symbols"
